mystery_boxes:
  basic_box:
    name: "&aBasic Mystery Box"
    material: PLAYER_HEAD
    texture: "base64_texture_code_here"
    lore:
      - "&7Right-click to open!"
      - "&fContains common rewards."
      - "&6★ &eWorth: &a11.99k"
    rewards:
      common:
        chance: 50
        items:
          - "IRON_INGOT:10"
          - "GOLD_INGOT:5"
        command:
          - "give %player% diamond 1"
        message:
          - "tell %player% &7★ &fYou have received a &aCommon &freward! &7★"
      rare:
        chance: 30
        items:
          - "DIAMOND:2"
        command:
          - "give %player% minecraft:diamond_sword 1"
        message:
          - "tell %player% &7★ &fYou have received a &aRare &freward! &7★"
      epic:
        chance: 15
        items:
          - "DIAMOND:2"
          - "ANCIENT_DEBRIS:4"
        command:
          - "give %player% minecraft:netherite_sword 1"
          - "give %player% minecraft:netherite_helmet 1"
        message:
          - "tell %player% &7★ &fYou have received a &aEpic &freward! &7★"
      legendary:
        chance: 5
        items:
          - "DIAMOND_BLOCK:10"
          - "NETHERITE_INGOT:1"
        command:
          - "give %player% minecraft:shulker_box 1"
          - "eco add %player% 20000"
        message:
          - "tell %player% &7★ &fYou have received a &aLegendary &freward! &7★"